server:
  port: 8080
spring:
  application:
    name: user
  profiles:
    active:
      - local

---

spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${RABBIT_URL}
broker:
  queue:
    email:
      name: default.email